### ISSUE TITLE
When you load the website on OBS the changelog pop-up blocks the screen

### ISSUE THREAD

**Issue by KingKusuo** [Gnitoon/ppShow#2]
![image](https://user-images.githubusercontent.com/69478539/152054614-2e8d5d96-5e17-412a-b131-d4fe11ffeee7.png)

Usually it would only load up the emotes from the channel, but now the changelog screen blocks up the emotes and there aren't any ways to remove it from the OBS program, is there a way to fix this issue? :/

**Comment by Gnitoon** [comment]
Done!

In latest version add ?hide=news to URL, also thought that connecting might be an issue as well, so I added an autoConnect optional parameter to toggle

Examples
hide: https://pp-show.vercel.app/?hide=news#channel
hide news and info+autoConnect: https://pp-show.vercel.app/?hide=news,info&autoConnect=true#channel

- You have to reload the page for autoConnect take effect

Sorry for taking some time to fix FeelsBadMan

**Comment by KingKusuo** [comment]
Thank you so much, this was very important for me, keep up the good work :)
